version: 2
jobs:
  build:
    docker:
      - image: gabaconrado/peculiar-fox:0.0
    steps:
      - checkout
      - run:
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -q -r etc/base/requirements.txt
            pip install -q -r etc/development/requirements.txt
      - run:
          name: Running tests
          command: |
            . venv/bin/activate
            cd src && pytest tests
